# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - DJANGO='1.8' REVERSION='1.9'  EXTRA=''
    - DJANGO='1.8' REVERSION='1.10.1' EXTRA=''
    - DJANGO='1.9' REVERSION='1.10' EXTRA=''
    - DJANGO='1.8' REVERSION='1.9'  EXTRA='diff-match-patch'
    - DJANGO='1.8' REVERSION='1.10.1'  EXTRA='diff-match-patch'
    - DJANGO='1.9' REVERSION='1.10' EXTRA='diff-match-patch'

install:
    - pip install --upgrade pip
    - pip install Django==$DJANGO.\*
    - pip install django-reversion==$REVERSION.\*
    - pip install . django-tools coveralls $EXTRA

script:
    - python --version
    - pip freeze
    - coverage run --source=reversion_compare runtests.py

after_success:
    - coverage combine
    - coverage report
    - coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
