# Config file for automatic testing at travis-ci.org

sudo: required
dist: trusty
# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
group: deprecated-2017Q4

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py27-django18-dmp
    - TOXENV=py27-django18
    - TOXENV=py27-django110-dmp
    - TOXENV=py27-django110
    - TOXENV=py27-django111-dmp
    - TOXENV=py27-django111
    - TOXENV=py34-django18-dmp
    - TOXENV=py34-django18
    - TOXENV=py34-django110-dmp
    - TOXENV=py34-django110
    - TOXENV=py34-django111-dmp
    - TOXENV=py34-django111
    - TOXENV=py35-django18-dmp
    - TOXENV=py35-django18
    - TOXENV=py35-django110-dmp
    - TOXENV=py35-django110
    - TOXENV=py35-django111-dmp
    - TOXENV=py35-django111
    - TOXENV=py36-django111-dmp
    - TOXENV=py36-django111

matrix:
    fast_finish: true

before_install:
    # work around https://github.com/travis-ci/travis-ci/issues/8363
    - pyenv global system 3.5

install:
    - pip install --upgrade pip
    - travis_retry pip install 'tox>=2.3.1' coveralls

script:
    - pip freeze
    - travis_retry tox

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
