# https://github.com/actions/setup-python

name: CI

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        python-version: [3.9, 3.8, 3.7]
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Install package'
      run: |
        pip3 install -U pip
        make install-poetry
        poetry lock
        poetry show --tree
        make install
        pip3 install tox-gh-actions

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'List all tox test environments'
      run: |
        make tox-listenvs

    - name: 'Run tests with Python v${{ matrix.python-version }}'
      run: |
        make tox

    - name: 'Upload coverage report'
      run: bash <(curl -s https://codecov.io/bash)

    - name: 'Run linters'
      if: matrix.python-version == '3.8'
      run: |
        make lint
