# https://github.com/actions/setup-python

name: Test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: 'Python ${{ matrix.python-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.9", "3.8", "3.7"]
        os: [ubuntu-latest] # TODO: macOS-latest, windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'fetch master'
      run: |
        git fetch origin master
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Install package'
      run: |
        pip3 install -U pip
        make install-poetry
        poetry lock
        poetry show --tree
        make install
        pip3 install tox-gh-actions

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'List all tox test environments'
      run: |
        make tox-listenvs

    - name: 'Run tests with Python v${{ matrix.python-version }}'
      run: |
        make tox

    - name: 'Upload coverage report'
      run: bash <(curl -s https://codecov.io/bash)
