# https://github.com/actions/setup-python

name: Test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: '${{ matrix.os }} Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # TODO: macOS-latest, windows-latest ;)
        python-version: ["3.10", "3.9", "3.8"]
        django: ["2.2", "3.2", "4.0"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'fetch master'
      run: |
        git fetch origin master
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Install package'
      run: |
        pip3 install poetry
        make install

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'List all tox test environments'
      run: |
        make tox-listenvs

    - name: 'Run tests on ${{ matrix.os }} with Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
      run: |
        poetry run tox -e python-django${{ matrix.django }}

    - name: 'Upload coverage report'
      run: bash <(curl -s https://codecov.io/bash)
